services:
  technovalab.irrigo.api:
    image: ${DOCKER_REGISTRY-}technovalabirrigoapi
    container_name: irrigo-api
    build:
      context: .
      dockerfile: src/TechNovaLab.Irrigo.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=irrigo-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
  