services:
  technovalab.irrigo.api:
    image: ${DOCKER_REGISTRY-}technovalabirrigoapi
    container_name: irrigo-api
    build:
      context: .
      dockerfile: src/TechNovaLab.Irrigo.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
  