services:
  technovalab.irrigo.api:
    image: ${DOCKER_REGISTRY-}technovalabirrigoapi
    build:
      context: .
      dockerfile: src/TechNovaLab.Irrigo.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development